### ISSUE TITLE
The "start_codons"/"stop_codons" parameter has never been used!

### ISSUE THREAD

**Issue by crazyxiaoj** [Chokyotager/ORFFinder#1]
I looked at your source code and found that in `getORFs` and two other functions, the `start_codons` parameter is provided for modification, but not passed to the `findSense` function below.

![image](https://github.com/user-attachments/assets/1cfe0172-39de-493f-9978-29944522c7bf)
The figure above shows that you did not pass the `start_codons` parameter into `findSense` function.

**Comment by Chokyotager** [comment]
Thanks for letting me know - it's fixed now in the latest commit
